# Generated by Django 3.2.8 on 2021-12-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20211125_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardversion',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
